---
- name: Add apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367

- name: Add apt repository
  apt_repository:
    repo: "deb http://ppa.launchpad.net/ansible/ansible/ubuntu {% if ansible_distribution == 'Debian' %}bionic{% else %}{{ ansible_distribution_release }}{% endif %} main"
    filename: ansible
    update_cache: true

- name: Install required packages
  apt:
    name: "{{ item }}"
  with_items:
    - ansible
    - python-yaml
    - python-jmespath
